### ISSUE TITLE
Setting noclientlog to true fails (because of ratelimit in Dockerfile)

### ISSUE THREAD

**Issue by mdavids** [simonrupf/docker-chronyd#3]
One can not just change 'false' to 'true' here:

https://github.com/simonrupf/docker-chronyd/blob/adffd8506859f0e395e40ca6d816223f3c3d06ca/vars#L22

Because it conflicts with:

```
# default configuration
ENV NTP_DIRECTIVES="ratelimit\nrtcsync"
```

in the Dockerfile.

**Comment by simonrupf** [comment]
For future reference, the error message logged in that case is:
```
Fatal error : Rate limiting cannot be enabled with noclientlog
```

Hence the solution is to remove the `ratelimit` directive from the `NTP_DIRECTIVES` environment variable, by setting it explicitly. For example, this will work:

```sh
docker run -d --env NOCLIENTLOG=true --env NTP_DIRECTIVES=rtcsync simonrupf/chronyd
```
