### ISSUE TITLE
Fatal error : Another chronyd may already be running (pid=1), check /var/run/chrony/chronyd.pid

### ISSUE THREAD

**Issue by tracure1337** [simonrupf/docker-chronyd#7]
Discussed here as well https://github.com/direktiv/vinitd/issues/12

This  happens when running in docker. And causes chrony to crash hard.
Only way to fix is

docker compose up -d --force-recreate --remove-oprhans

**Comment by simonrupf** [comment]
It seems the docker compose file is inconsistent with the run.sh example, where we:
https://github.com/simonrupf/docker-chronyd/blob/5dee8060748d7bd0084a70ac8e886df472894bab/run.sh#L34-L37

If the /run/chrony volume, where the PID is located (/var/run being a symlink to /run on Alpine Linux), is a tmpfs, it will get recreated (empty) on service stop or restart.

**Comment by simonrupf** [comment]
Let me know if the updated compose-file resolves your issue, otherwise feel free to re-open this.

**Comment by tracure1337** [comment]
I was a custom Dockerfile but I took all the clues from your image. 
Anyways I switched to yours and everything works lke a charm!
Thanks and sorry :-)
